### ISSUE TITLE
Investigate articles about Win10Clean

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/Win10Clean#5]
Recently this application went up on many sketchy websites at the same time and date.

**Comment by MajorGeek** [comment]
We posted it on MajorGeeks and many of these websites simply monitor others and add files but, in a sketchy way, as you say. We've been here for 17 years.

**Comment by HawaiiBeach** [comment]
https://web.archive.org/web/20170814210047/http://technewsdir.com/win10clean-windows-10-system-tweaker for example, obviously a bot

And yes, I suspect that there are bots floating around spreading this application from MajorGeek. For a very long time this application have not been known by anyone - now suddenly blowing up

Also @MajorGeek thanks for spreading this application and the feedback (since I recive 0)

**Comment by MajorGeek** [comment]
My pleasure, hopefully, my review helps but personally, I thought it was a simple, useful app.
